# Generated by Django 3.2.5 on 2021-07-18 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('stdid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll', models.IntegerField()),
                ('admno', models.IntegerField()),
                ('sname', models.CharField(max_length=70)),
                ('mname', models.CharField(max_length=70)),
                ('fname', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
