# Generated by Django 3.2.5 on 2021-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='dob',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='admno',
            field=models.IntegerField(verbose_name='Admission No.'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='contact',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='fname',
            field=models.CharField(max_length=70, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='mname',
            field=models.CharField(max_length=70, verbose_name='Mother Name'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='roll',
            field=models.IntegerField(verbose_name='Roll No.'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='sname',
            field=models.CharField(max_length=70, verbose_name='Student Name'),
        ),
    ]
