# Generated by Django 3.2.5 on 2021-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210718_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='stdid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
