# Generated by Django 3.2.5 on 2021-07-18 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentuser_stdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='stdid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
