# Generated by Django 3.2.5 on 2021-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentuser_stdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='stdid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
