# Generated by Django 3.2.5 on 2021-07-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentuser_stdid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('chname', models.CharField(max_length=70, verbose_name='Chapter Name')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=70, verbose_name='Class Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=70, verbose_name='Subject Name')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('topname', models.CharField(max_length=70, verbose_name='Topic Name')),
                ('chid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.chapter')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.AddField(
            model_name='chapter',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
    ]
