# Generated by Django 3.2.5 on 2021-07-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210718_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='classid',
        ),
    ]
