# Generated by Django 3.2.5 on 2021-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_subject_classid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSubject',
            fields=[
                ('asssubid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('classid', models.ManyToManyField(to='students.Class')),
                ('subname', models.ManyToManyField(to='students.Subject')),
            ],
        ),
    ]
