# Generated by Django 3.2.5 on 2021-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_assignsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classid',
            field=models.ManyToManyField(to='students.Class'),
        ),
        migrations.DeleteModel(
            name='AssignSubject',
        ),
    ]
