# Generated by Django 3.2.5 on 2021-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='std1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=100)),
                ('subject_1', models.CharField(max_length=100)),
                ('competency_1', models.CharField(max_length=2000)),
                ('playlist_link_1', models.URLField()),
                ('worksheet_link_1', models.URLField()),
                ('subject_2', models.CharField(max_length=100)),
                ('competency_2', models.CharField(max_length=2000)),
                ('playlist_link_2', models.URLField()),
                ('worksheet_link_2', models.URLField()),
            ],
        ),
    ]
