# Generated by Django 3.2.5 on 2021-09-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chname', models.CharField(max_length=50, verbose_name='Chapter Name')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(verbose_name='Date Added')),
                ('videotitle', models.CharField(default='', max_length=100, verbose_name='Video Title')),
                ('videourl', models.CharField(default='', max_length=100, verbose_name='Video URL')),
                ('assignmenturl', models.CharField(default='', max_length=100, verbose_name='Assignment URL')),
                ('learningoutcome', models.CharField(default='', max_length=100, verbose_name='Learning Outcome')),
                ('chname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chapter', verbose_name='Chapter')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Class')),
                ('subjectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Subject')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subjectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Subject'),
        ),
        migrations.CreateModel(
            name='AssignSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Class')),
                ('subjectname', models.ManyToManyField(to='home.Subject', verbose_name=' List of Subjects')),
            ],
        ),
    ]
