# Generated by Django 3.2.5 on 2021-09-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std1',
            name='competency_1',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='std1',
            name='competency_2',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='std1',
            name='subject_1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='std1',
            name='subject_2',
            field=models.TextField(max_length=100),
        ),
    ]
