# Generated by Django 3.2.5 on 2021-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210928_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('chno', models.CharField(max_length=100)),
                ('chname', models.CharField(max_length=100)),
                ('partno', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('videourl', models.CharField(max_length=100)),
            ],
        ),
    ]
