# Generated by Django 3.2.5 on 2021-08-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_assignnewsubject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignNewSubject',
        ),
    ]
