# Generated by Django 3.2.5 on 2021-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_assignnewsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20)),
                ('subjectname', models.CharField(max_length=20)),
                ('chname', models.CharField(max_length=50)),
            ],
        ),
    ]
