# Generated by Django 3.2.5 on 2021-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=100)),
                ('subject_1', models.TextField(max_length=100)),
                ('competency_1', models.TextField(max_length=2000)),
                ('playlist_link_1', models.URLField()),
                ('worksheet_link_1', models.URLField()),
                ('subject_2', models.TextField(max_length=100)),
                ('competency_2', models.TextField(max_length=2000)),
                ('playlist_link_2', models.URLField()),
                ('worksheet_link_2', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='recommended',
        ),
    ]
