# Generated by Django 3.2.5 on 2021-10-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211012_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content',
            new_name='all_content',
        ),
    ]
