# Generated by Django 3.2.5 on 2021-08-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard'),
        ),
    ]
