# Generated by Django 3.2.5 on 2021-08-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_chapters_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='chname',
            field=models.CharField(max_length=50, verbose_name='Chapter Name'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='subjectname',
            field=models.CharField(max_length=20, verbose_name='Subject'),
        ),
    ]
