# Generated by Django 3.2.5 on 2021-08-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_chapters_subjectname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapters',
            new_name='Chapter',
        ),
    ]
