# Generated by Django 3.2.5 on 2021-08-08 16:35

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_chapter_subjectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subjectname',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subjectname',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='subjectname', chained_model_field='subjectname', horizontal=True, to='home.AssignSubject', verbose_name='Subject'),
        ),
    ]
