# Generated by Django 3.2.5 on 2021-08-08 16:37

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210808_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subjectname',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='Subject', chained_model_field='subjectname', horizontal=True, to='home.AssignSubject', verbose_name='Subject'),
        ),
    ]
