# Generated by Django 3.2.5 on 2021-08-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_chapter_subjectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subjectname',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subjectname',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
