# Generated by Django 3.2.5 on 2021-08-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chname', models.CharField(max_length=50, verbose_name='Chapter Name')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Class')),
                ('subjectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Subject')),
            ],
        ),
    ]
