# Generated by Django 3.2.5 on 2021-08-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210811_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subjectname',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subjectname',
            field=models.ManyToManyField(to='home.AssignSubject', verbose_name='Subject'),
        ),
    ]
