# Generated by Django 3.2.5 on 2021-08-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210811_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subjectname',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subjectname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.assignsubject', verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
