# Generated by Django 3.2.5 on 2021-08-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210811_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subjectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Subject'),
        ),
    ]
