# Generated by Django 3.2.5 on 2021-08-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_chapter_subjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subjectname',
            field=models.CharField(max_length=50, verbose_name='Subject'),
        ),
    ]
