# Generated by Django 3.2.5 on 2021-08-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_chapter_subjectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topname', models.CharField(max_length=50, verbose_name='Topic Name')),
                ('chname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chapter')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Class')),
                ('subjectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Subject')),
            ],
        ),
    ]
