# Generated by Django 3.2.5 on 2021-08-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='topname',
        ),
        migrations.AddField(
            model_name='content',
            name='learningoutcome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Learning Outcome'),
        ),
        migrations.AlterField(
            model_name='content',
            name='chname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chapter', verbose_name='Chapter'),
        ),
    ]
