# Generated by Django 3.2.5 on 2021-08-12 15:55

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210812_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='content',
            name='assignmenturl',
            field=models.URLField(blank=True, max_length=500, verbose_name='Assignment URL'),
        ),
        migrations.AddField(
            model_name='content',
            name='videourl',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Chapter'),
        ),
    ]
