# Generated by Django 3.2.5 on 2021-08-12 16:44

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210812_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='assignmenturl',
            field=models.URLField(max_length=500, verbose_name='Assignment URL'),
        ),
        migrations.AlterField(
            model_name='content',
            name='learningoutcome',
            field=models.CharField(max_length=100, verbose_name='Learning Outcome'),
        ),
        migrations.AlterField(
            model_name='content',
            name='videourl',
            field=embed_video.fields.EmbedVideoField(verbose_name='Video URL'),
        ),
    ]
