# Generated by Django 3.2.5 on 2021-08-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210812_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='added',
            field=models.DateField(),
        ),
    ]
