# Generated by Django 3.2.5 on 2021-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_content_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='added',
            field=models.DateField(auto_now=True),
        ),
    ]
