# Generated by Django 3.2.5 on 2021-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_content_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='videotitle',
            field=models.CharField(default='', max_length=100, verbose_name='Video Title'),
        ),
    ]
