# Generated by Django 3.2.5 on 2021-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_content_videotitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='newContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(default='', max_length=100)),
                ('subjectname', models.CharField(default='', max_length=100)),
                ('chname', models.CharField(default='', max_length=100)),
                ('added', models.DateField()),
                ('videotitle', models.CharField(default='', max_length=100)),
                ('videourl', models.CharField(default='', max_length=100)),
                ('assignmenturl', models.CharField(default='', max_length=100)),
                ('learningoutcome', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
