# Generated by Django 3.2.5 on 2021-08-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210815_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontent',
            name='classname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='subjectname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
