# Generated by Django 3.2.5 on 2021-08-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210816_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontent',
            name='chname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.standard', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='subjectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject', verbose_name='Subject'),
        ),
    ]
